config/routes.rb
Rails.application.routes.draw do
  resources :pages, except: [:show]
  get "pages/:permalink" => "pages#permalink", as: "permalink"  # using it in ruby: permalink_path
  root to: "home#index"
  resources :movies, only: %i[index show]
  resources :production_companies, only: %i[index show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
  has_many :movies, through: :movie_genres
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :production_company

  has_many :movie_genres
  has_many :genres, through: :movie_genres

  validates :title, :year, :duration, :description, :average_vote, presence: true

  validates :title, uniqueness: true

  validates :year, :duration, numericality: { only_integer: true }

  validates :average_vote, numericality: true

  def genres_list
    genres.map(&:name).join(", ")
  end
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/production_company.rb
class ProductionCompany < ApplicationRecord
  has_many :movies
  validates :name, presence: true, uniqueness: true

  def self.ordered_by_movies
    self.select("production_companies.*")
        .select("COUNT(production_companies.id) as movie_count")
        .left_joins(:movies)
        .group("production_companies.id")
        .order("movie_count DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :cms_pages
  def cms_pages
    Page.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.includes(:production_company)
                   .order("average_vote DESC")
                   .limit(10)
    @production_companies = ProductionCompany.ordered_by_movies
                                             .limit(10)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all.includes(:production_company).all.order("average_vote DESC")
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[edit update destroy]

  http_basic_authenticate_with name: "admin", password: "secret", except: [:permalink]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html do
          redirect_to permalink_path(@page.permalink), notice: "Page was successfully created."
        end
        format.json { render :show, status: :created, location: permalink_path(@page.permalink) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html do
          redirect_to permalink_path(@page.permalink), notice: "Page was successfully updated."
        end
        format.json { render :show, status: :ok, location: permalink_path(@page.permalink) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/production_companies_controller.rb
class ProductionCompaniesController < ApplicationController
  def index
    @production_companies = ProductionCompany.ordered_by_movies
  end

  def show
    @production_company = ProductionCompany.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/production_companies_helper.rb
module ProductionCompaniesHelper
end

app/views/common/_footer.html.erb
<hr>
<footer>
  <p><em>Copywrong IMDB 2021</em></p>
  <ul class="mt-5">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Top 100 Movies", movies_path %></li>
    <li><%= link_to "Top Production Companies", production_companies_path %></li>
    <% cms_pages.each do | page |%>
      <li><%= link_to page.title, permalink_path(page.permalink) %> </li>
    <% end %>
  </ul>
</footer>

app/views/home/index.html.erb
<div class="columns">
  <div class="column">
    <h2 class="title is-2">Top 10 Movies</h2>
    <ol class="ml-5">
      <% @movies.each do | movie | %>
        <li>
          <%= link_to movie.title, movie %>
          <em>(<%= movie.production_company.name %>)</em>
        </li>
      <% end %>
    </ol>
  </div>
  <div class="column">
    <h2 class="title is-2">Top 10 Production Companies</h2>
    <ol class="ml-5">
      <%= render @production_companies %>
    </ol>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:html_title) + " - " if content_for?(:html_title) %>Top 100 Movies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="section">
      <div class="container">
        <h1 class="title is-1"><%= link_to 'Top Movies From IMDB', root_path %></h1>
      </div>
      <%= yield %>

      <% if controller_name == 'home'%>
      <p>
      There is no place like home!!
      </p>
      <% else %>
        <%= render partial: 'common/footer'%>
      <% end %>

    </section>
  </body>


</html>

app/views/movies/_movie.html.erb
<h2 class="title is-2">
  <% if show_link %>
    <%= link_to movie.title, movie %>
  <% else %>
    <%= movie.title %>
  <% end %>
</h2>

<article class="message is-dark">
  <div class="message-header">
    <p>Description</p>
  </div>
  <div class="message-body">
    <%= movie.description %>
  </div>
</article>

<progress class="progress is-info" value="<%= movie.average_vote %>" max=10>
  <%= movie.average_vote %>
</progress>

<p>
  <strong>Rating: </strong>
  <%= movie.average_vote %>
</p>

<p>
  <strong>Release Year: </strong>
  <%= movie.year %>
</p>

<p>
  <strong>Duration</strong>
  <%= movie.duration %> minutes
</p>

<p>
  <strong>Production Company: </strong>
  <%= link_to movie.production_company.name, movie.production_company %>
</p>

<p>
  <strong>Genres: </strong>
  <%= movie.genres_list %>
</p>

<hr>

app/views/movies/index.html.erb
<h2 class="title is-2">Top 100 Movies</h2>

  <%= render partial: @movies, locals: {show_link: true}%>

app/views/movies/show.html.erb
<% content_for(:html_title) { @movie.title }%>



<%= render partial: 'movies/movie', object: @movie, locals: {show_link: false}%>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title , class: 'label'%>
    <%= form.text_field :title, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :content, class: 'label' %>
    <%= form.text_area :content, class: 'textarea' %>
  </div>

  <div class="field">
    <%= form.label :permalink, class: 'label' %>
    <%= form.text_field :permalink, class: 'input' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h2 class="title is-4">Editing Page</h2>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="title is-4">Pages</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= truncate page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', permalink_path(page.permalink), class: 'button is-info' %></td>
        <td><%= link_to 'Edit', edit_page_path(page), class: 'button is-warning' %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path, class: 'button is-primary' %>

app/views/pages/new.html.erb
<h2 class="title is-4">New Page</h2>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/permalink.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/production_companies/_production_company.html.erb
<li>
  <%= link_to production_company.name, production_company %>
  <em>(<%= pluralize production_company.movie_count, "Top Movie" %>)</em>
</li>

app/views/production_companies/index.html.erb
<h2 class="title is-2">Top Production Companies</h2>
    <ol class="ml-5">
      <%= render @production_companies %>
    </ol>

app/views/production_companies/show.html.erb
<h2 class="title is-2"><%= @production_company.name%></h2>

<p class='mb-5'>
  This production company made <%= @production_company.movies.count %> of the top 100 movies.
</p>

<h3 class='title is-3'>Movies Made By <%= @production_company.name %></h3>
<ul>
  <% @production_company.movies.each do |movie| %>
    <li><%= link_to movie.title, movie %> with a rating of <%= movie.average_vote %> / 10</li>
  <% end %>
</ul>

<h3 class='title is-3'>Movies Made By <%= @production_company.name %></h3>
<ul>
  <%= render partial: @production_company.movies, locals: { show_link: true } %>
</ul>